# Generated by Django 3.0.4 on 2020-03-23 04:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_base',
            name='phone',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(6000000000)]),
        ),
        migrations.AlterField(
            model_name='data_base',
            name='profile',
            field=models.CharField(choices=[('Student', 'Student'), ('Working', 'Working'), ('Retired', 'Retired')], max_length=20),
        ),
    ]
