# Generated by Django 3.0.4 on 2020-03-23 07:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0002_auto_20200323_0418'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_base',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 23, 7, 14, 41, 952749)),
        ),
    ]
