# Generated by Django 3.0.4 on 2020-03-23 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0003_data_base_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_base',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
